name: lucky_draw_csv_app
description: "A new Flutter project"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  file_picker: ^6.1.1
  csv: ^5.1.1
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.2
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/slot_machine.mp4
    - assets/audio/winner.mp4
    - assets/images/logo.png